name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main   # change si nécessaire
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Dépendances
      - name: Install dependencies
        run: flutter pub get

      # Build Web
      - name: Build Flutter Web
        run: flutter build web --release

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t my-flutter-web-app:latest .

      # (Optionnel) Push vers DockerHub ou un autre registry
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-flutter-web-app:latest mydockerhubuser/my-flutter-web-app:latest
          docker push mydockerhubuser/my-flutter-web-app:latest
          